version: '3.8'

services:
  spark-env:
    build: .
    container_name: ambev_lakehouse_env
    ports:
      - "8888:8888" # Jupyter Lab
      - "4040:4040" # Spark UI
      - "8501:8501" # Streamlit
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - CHOWN_HOME=yes
      - GRANT_SUDO=yes
      - SPARK_SUBMIT_OPTS=-Dspark.jars.packages=io.delta:delta-spark_2.12:3.1.0
    user: root
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''