version: '3.8'
services:
  spark-env:
    build: .
    container_name: ambev_lakehouse_env
    ports:
      - "8888:8888"
      - "4040:4040"
      - "8501:8501"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - CHOWN_HOME=yes
